// ===== Featured Yachts - single source of truth =====
// Generated by /admin/featured-yachts.html - Featured Image Maintenance
// You can also edit this file manually if preferred.
//
// Schema per entry:
//   image       - relative path to hero image (e.g. images/yachts/featured/foo.jpg)
//   name        - display title shown above the description
//   description - body copy under the title
//   link        - destination URL for the primary "Inquire" button (usually contact.html)
//   linkText    - label for the primary button
//   pdf         - optional. Relative path to a Full Details PDF in documents/yachts/featured/
//                 OR an absolute URL to an externally hosted spec sheet. Empty/missing = button hidden.
//   kuula       - optional. Sanitized <iframe> embed code for a Kuula 360 tour. Must point at
//                 kuula.co. Empty/missing = no 360 section, no badge.
//   youtube     - optional. A YouTube video ID (e.g. "8Sfu5DoYrBw"). Stored as the bare 11-char ID;
//                 rendered as a responsive 16:9 player in the shared lightbox via a "Watch Video"
//                 badge + link. Empty/missing = no video badge, no video link.
//   page        - optional. Relative path to a dedicated listing page (e.g. yachts/fringe-benefits.html).
//                 When present, the card image + title + primary action link to this page.
//                 Empty/missing = primary action is the standard mailto Inquire.

const featuredYachts = [
    {
        image: "images/yachts/featured/riviera545suv.jpg",
        name: "2020 Riviera 545 SUV, \"Fringe Benefits\" $1,295,000",
        description: "The Riviera 545 SUV blends luxury cruising with adventure-ready capability. Three staterooms, a full-beam master, an expansive cockpit, and the signature Riviera build quality make her ideal for extended family voyages and weekend getaways alike.",
        link: "contact.html",
        linkText: "Inquire",
        pdf: "documents/yachts/featured/2020-Riviera-545_SUV.pdf",
        kuula: "<iframe src=\"https://kuula.co/share/collection/7MBqZ?logo=1&info=0&fs=1&vr=0&gyro=0&thumbs=1&keys=0\" width=\"100%\" height=\"640\" frameborder=\"0\" allow=\"xr-spatial-tracking; gyroscope; accelerometer\" allowfullscreen ></iframe>",
        youtube: "8Sfu5DoYrBw",
        page: "yachts/fringe-benefits.html"
    },
    {
        image: "images/yachts/featured/southern-wind.jpg",
        name: "1991 Southern Wind 72, \"Fortunato\" - $395,000",
        description: "Because of their renowned build quality and Bruce Farr’s exceptional design, the Southern Wind 72 is equally at home crossing oceans, effortlessly clicking off 200‑mile days or competing in long‑distance racing!",
        link: "contact.html",
        linkText: "Inquire",
        pdf: "documents/yachts/featured/1991-Southern_Wind-Bruce_Farr_Fast_72.pdf",
        kuula: "<iframe src=\"https://kuula.co/share/collection/7MFLp?logo=-1&info=1&fs=1&vr=0&gyro=0&thumbs=1&keys=0\" width=\"100%\" height=\"640\" frameborder=\"0\" allow=\"xr-spatial-tracking; gyroscope; accelerometer\" allowfullscreen ></iframe>",
        page: "yachts/fortunato.html"
    },
    {
        image: "",
        name: "Featured Listing",
        description: "Details about this featured yacht will appear here.",
        link: "contact.html",
        linkText: "Inquire",
        pdf: "",
        kuula: "",
        youtube: "",
        page: ""
    },
    {
        image: "",
        name: "Featured Listing",
        description: "Details about this featured yacht will appear here.",
        link: "contact.html",
        linkText: "Inquire",
        pdf: "",
        kuula: "",
        youtube: "",
        page: ""
    },
    {
        image: "",
        name: "Featured Listing",
        description: "Details about this featured yacht will appear here.",
        link: "contact.html",
        linkText: "Inquire",
        pdf: "",
        kuula: "",
        youtube: "",
        page: ""
    },
    {
        image: "",
        name: "Featured Listing",
        description: "Details about this featured yacht will appear here.",
        link: "contact.html",
        linkText: "Inquire",
        pdf: "",
        kuula: "",
        youtube: "",
        page: ""
    }
];

function isFilledYacht(y) {
    // A slot counts as "filled" if it has either an image, or a real (non-placeholder) name.
    if (y.image && y.image.trim()) return true;
    if (y.name && y.name !== 'Featured Listing') return true;
    return false;
}

// Strip the price portion from a yacht name so the email subject is clean.
// "1995 Manta 42 Mark II - SANGARIS $259,000.00" -> "1995 Manta 42 Mark II - SANGARIS"
function _fyStripPrice(name) {
    return (name || '').replace(/[\s,\-]*\$[\d,\.]+.*$/, '').trim();
}
function _fyInquireMailto(name) {
    const subject = encodeURIComponent(_fyStripPrice(name) + ' Inquiry');
    return `mailto:clark@haleyyachts.com?subject=${subject}`;
}

// Re-sanitize the stored Kuula iframe at render time as a defense-in-depth check.
// Admin already sanitizes on save; this also rejects any hand-edited entries that
// don't point at kuula.co.
function _fySanitizeKuula(raw) {
    if (!raw || !raw.trim()) return '';
    const tagStart = raw.match(/<iframe\b[^>]*>/i);
    if (!tagStart) return '';
    const openTag = tagStart[0];
    const srcMatch = openTag.match(/\bsrc\s*=\s*(['"])(.*?)\1/i);
    if (!srcMatch) return '';
    const src = srcMatch[2];
    if (!/(^|\/\/|\.)kuula\.co(\/|$)/i.test(src)) {
        console.warn('[Kuula] Rejected iframe at render: src is not kuula.co ->', src);
        return '';
    }
    const allowed = ['src','width','height','frameborder','allow','allowfullscreen','style'];
    const attrs = {};
    const attrRe = /(\w[\w-]*)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'>]+))|(\ballowfullscreen\b)/gi;
    let m;
    while ((m = attrRe.exec(openTag)) !== null) {
        if (m[5]) { attrs['allowfullscreen'] = ''; continue; }
        const name = m[1].toLowerCase();
        if (!allowed.includes(name)) continue;
        attrs[name] = m[2] !== undefined ? m[2] : (m[3] !== undefined ? m[3] : (m[4] || ''));
    }
    const parts = ['<iframe'];
    for (const k of allowed) {
        if (!(k in attrs)) continue;
        if (k === 'allowfullscreen') { parts.push('allowfullscreen'); continue; }
        const v = String(attrs[k]).replace(/"/g, '&quot;');
        parts.push(`${k}="${v}"`);
    }
    parts.push('></iframe>');
    return parts.join(' ');
}

// Extract a clean YouTube video ID from whatever is stored. Admin already
// normalizes to a bare ID on save; this also handles a hand-edited full URL
// (watch?v=, youtu.be/, /shorts/, /embed/) and rejects anything that isn't a
// plausible 11-char YouTube ID. Returns the ID or '' .
function _fyYouTubeId(raw) {
    if (!raw || !raw.trim()) return '';
    const s = raw.trim();
    // Bare ID already.
    if (/^[A-Za-z0-9_-]{11}$/.test(s)) return s;
    let m =
        s.match(/[?&]v=([A-Za-z0-9_-]{11})/) ||
        s.match(/youtu\.be\/([A-Za-z0-9_-]{11})/) ||
        s.match(/\/(?:shorts|embed)\/([A-Za-z0-9_-]{11})/);
    if (m) return m[1];
    console.warn('[YouTube] Could not extract a video ID from ->', raw);
    return '';
}

// Build a privacy-friendly, responsive embed iframe for the lightbox.
function _fyYouTubeIframe(id) {
    const src = `https://www.youtube-nocookie.com/embed/${id}?rel=0&autoplay=1`;
    return `<iframe src="${src}" width="100%" height="100%" frameborder="0" ` +
        `allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" ` +
        `allowfullscreen></iframe>`;
}

// Inject the 360 CSS + modal scaffold once. Card grid renders many times;
// styles + modal markup inject once and are reused for every card.
function _fyInjectKuulaStyles() {
    if (document.getElementById('fy-kuula-styles')) return;
    const css = `
.card .card-img-wrap { position: relative; }
.card .card-img { position: relative; }
.card .card-img-link { display: block; }
.fy-kuula-badge {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    background: rgba(10, 22, 40, 0.88);
    color: #fff;
    font-size: 0.72rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 1.2px;
    padding: 7px 12px;
    border-radius: 3px;
    border: 1px solid rgba(33, 203, 234, 0.55);
    cursor: pointer;
    position: absolute;
    /* Anchored to the BOTTOM-right so it never collides with a PRICE
       REDUCTION bar that's baked across the TOP of a featured image. */
    bottom: 12px;
    right: 12px;
    z-index: 2;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.25);
    transition: background 0.2s, transform 0.2s, border-color 0.2s;
}
.fy-kuula-badge:hover,
.fy-kuula-badge:focus-visible {
    background: #21cbea;
    border-color: #21cbea;
    transform: translateY(-1px);
    outline: none;
}
.fy-kuula-badge::before {
    content: '\\25F0';
    font-size: 0.95rem;
    line-height: 1;
}
.fy-kuula-link {
    background: none;
    border: none;
    padding: 0;
    font: inherit;
    cursor: pointer;
    font-size: 0.82rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: #21cbea;
}
.fy-kuula-link:hover { color: #1aa8c4; }
.fy-kuula-link::after { content: ' \\2192'; transition: margin-left 0.2s; }
.fy-kuula-link:hover::after { margin-left: 4px; }

/* YouTube video badge - reuses the lightbox. Anchored BOTTOM-LEFT so it never
   collides with the 360 badge (bottom-right) when a yacht has both. */
.fy-video-badge {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    background: rgba(10, 22, 40, 0.88);
    color: #fff;
    font-size: 0.72rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 1.2px;
    padding: 7px 12px;
    border-radius: 3px;
    border: 1px solid rgba(220, 60, 60, 0.7);
    cursor: pointer;
    position: absolute;
    bottom: 12px;
    left: 12px;
    z-index: 2;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.25);
    transition: background 0.2s, transform 0.2s, border-color 0.2s;
}
.fy-video-badge:hover,
.fy-video-badge:focus-visible {
    background: #cc1f1f;
    border-color: #cc1f1f;
    transform: translateY(-1px);
    outline: none;
}
.fy-video-badge::before {
    content: '\\25B6';
    font-size: 0.8rem;
    line-height: 1;
}
.fy-video-link {
    background: none;
    border: none;
    padding: 0;
    font: inherit;
    cursor: pointer;
    font-size: 0.82rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: #cc1f1f;
}
.fy-video-link:hover { color: #a01818; }
.fy-video-link::after { content: ' \\2192'; transition: margin-left 0.2s; }
.fy-video-link:hover::after { margin-left: 4px; }

@media (max-width: 600px) {
    .fy-video-badge { font-size: 0.66rem; padding: 6px 10px; }
}

.fy-kuula-modal {
    position: fixed;
    inset: 0;
    background: rgba(5, 12, 24, 0.92);
    z-index: 10000;
    display: none;
    align-items: center;
    justify-content: center;
    padding: 24px;
}
.fy-kuula-modal.is-open { display: flex; }
.fy-kuula-modal-inner {
    position: relative;
    width: 100%;
    max-width: 1280px;
    aspect-ratio: 16 / 9;
    max-height: calc(100vh - 48px);
    background: #000;
    border-radius: 4px;
    overflow: hidden;
    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.55);
}
.fy-kuula-modal-frame {
    position: absolute;
    inset: 0;
}
.fy-kuula-modal-frame iframe {
    width: 100%;
    height: 100%;
    border: 0;
    display: block;
}
.fy-kuula-modal-close {
    position: absolute;
    top: 10px;
    right: 10px;
    width: 40px;
    height: 40px;
    border-radius: 50%;
    border: none;
    background: rgba(10, 22, 40, 0.85);
    color: #fff;
    font-size: 1.4rem;
    line-height: 1;
    cursor: pointer;
    z-index: 2;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: background 0.2s;
}
.fy-kuula-modal-close:hover,
.fy-kuula-modal-close:focus-visible {
    background: #21cbea;
    outline: none;
}
@media (max-width: 600px) {
    .fy-kuula-modal { padding: 0; }
    .fy-kuula-modal-inner { border-radius: 0; max-height: 100vh; aspect-ratio: auto; height: 100vh; }
    .fy-kuula-badge { font-size: 0.66rem; padding: 6px 10px; }
}
`;
    const style = document.createElement('style');
    style.id = 'fy-kuula-styles';
    style.textContent = css;
    document.head.appendChild(style);

    // Build the single shared modal once.
    if (!document.getElementById('fy-kuula-modal')) {
        const modal = document.createElement('div');
        modal.id = 'fy-kuula-modal';
        modal.className = 'fy-kuula-modal';
        modal.setAttribute('role', 'dialog');
        modal.setAttribute('aria-modal', 'true');
        modal.setAttribute('aria-label', '360 walkthrough');
        modal.innerHTML = `
            <div class="fy-kuula-modal-inner">
                <div class="fy-kuula-modal-frame"></div>
                <button type="button" class="fy-kuula-modal-close" aria-label="Close 360 walkthrough">&times;</button>
            </div>
        `;
        document.body.appendChild(modal);

        // Close on backdrop click, close button, or Escape.
        modal.addEventListener('click', (e) => {
            if (e.target === modal || e.target.closest('.fy-kuula-modal-close')) {
                _fyCloseKuula();
            }
        });
        document.addEventListener('keydown', (e) => {
            if (e.key === 'Escape' && modal.classList.contains('is-open')) {
                _fyCloseKuula();
            }
        });
    }
}

// Open the shared lightbox with the iframe HTML stashed on the trigger element.
// Iframe HTML lives on a data attribute so we don't depend on any DOM structure
// inside the card.
function _fyOpenKuula(trigger) {
    const modal = document.getElementById('fy-kuula-modal');
    if (!modal) return;
    const iframeHtml = trigger.getAttribute('data-kuula');
    if (!iframeHtml) return;
    modal.querySelector('.fy-kuula-modal-frame').innerHTML = iframeHtml;
    modal.classList.add('is-open');
    document.body.style.overflow = 'hidden';
    const closeBtn = modal.querySelector('.fy-kuula-modal-close');
    if (closeBtn) closeBtn.focus();
}

// Open the shared lightbox with a YouTube video. The trigger carries a bare
// video ID; the responsive iframe is built fresh each time (and is wiped on
// close, which stops playback).
function _fyOpenVideo(trigger) {
    const modal = document.getElementById('fy-kuula-modal');
    if (!modal) return;
    const id = _fyYouTubeId(trigger.getAttribute('data-video') || '');
    if (!id) return;
    modal.setAttribute('aria-label', 'Yacht video');
    modal.querySelector('.fy-kuula-modal-frame').innerHTML = _fyYouTubeIframe(id);
    modal.classList.add('is-open');
    document.body.style.overflow = 'hidden';
    const closeBtn = modal.querySelector('.fy-kuula-modal-close');
    if (closeBtn) closeBtn.focus();
}

function _fyCloseKuula() {
    const modal = document.getElementById('fy-kuula-modal');
    if (!modal) return;
    modal.classList.remove('is-open');
    // Wipe the iframe to stop audio/loading.
    modal.querySelector('.fy-kuula-modal-frame').innerHTML = '';
    modal.setAttribute('aria-label', '360 walkthrough');
    document.body.style.overflow = '';
}

// HTML-escape a string for safe insertion into a data-* attribute.
function _fyEscapeAttr(s) {
    return String(s)
        .replace(/&/g, '&amp;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
}

function renderFeaturedYachts(containerId) {
    const container = document.getElementById(containerId);
    if (!container) return;

    _fyInjectKuulaStyles();

    container.innerHTML = featuredYachts.filter(isFilledYacht).map(y => {
        // Vertically top-anchor the cover-crop. Several featured photos have a
        // "PRICE REDUCTION" banner baked across the TOP of the image; a centered
        // crop in the fixed-height card box (220px) clips that banner in half.
        // Anchoring to the top shows the full banner and trims only bottom water
        // foreground, which keeps every boat fully in frame.
        const imgStyle = y.image
            ? `background-image: url('${y.image}'); background-size: cover; background-position: center top;`
            : '';
        const imgLabel = y.image ? '' : 'Featured Yacht Image';
        const pdfLink = (y.pdf && y.pdf.trim())
            ? `<a href="${y.pdf}" class="card-link card-link-secondary" target="_blank" rel="noopener">Spec Sheet (PDF)</a>`
            : '';
        const inquireHref = _fyInquireMailto(y.name);
        const kuulaClean = _fySanitizeKuula(y.kuula);
        const kuulaDataAttr = kuulaClean
            ? ` data-kuula="${_fyEscapeAttr(kuulaClean)}"`
            : '';
        // Badge lives as a sibling of the image anchor (not inside it) so the
        // browser's anchor-navigation default never fires for badge clicks. A
        // nested <button> inside <a> is also invalid HTML.
        const kuulaBadge = kuulaClean
            ? `<button type="button" class="fy-kuula-badge" aria-label="Open 360 walkthrough"${kuulaDataAttr} onclick="_fyOpenKuula(this)">360&deg; Tour</button>`
            : '';
        const kuulaLink = kuulaClean
            ? `<button type="button" class="fy-kuula-link" aria-label="Open 360 walkthrough"${kuulaDataAttr} onclick="_fyOpenKuula(this)">View 360&deg; Tour</button>`
            : '';

        // YouTube video: stored as a bare ID, opens in the same lightbox.
        const videoId = _fyYouTubeId(y.youtube);
        const videoDataAttr = videoId ? ` data-video="${_fyEscapeAttr(videoId)}"` : '';
        const videoBadge = videoId
            ? `<button type="button" class="fy-video-badge" aria-label="Play yacht video"${videoDataAttr} onclick="_fyOpenVideo(this)">Video</button>`
            : '';
        const videoLink = videoId
            ? `<button type="button" class="fy-video-link" aria-label="Play yacht video"${videoDataAttr} onclick="_fyOpenVideo(this)">Watch Video</button>`
            : '';

        // If a dedicated listing page exists, image + title + primary action
        // all point at it. Otherwise the image and title are plain (no anchor)
        // and the primary action falls back to the standard mailto Inquire.
        const hasPage = !!(y.page && y.page.trim());
        const pageHref = hasPage ? y.page : '';
        const imgEl = `<div class="card-img" style="${imgStyle}">${imgLabel}</div>`;
        const imgAnchored = hasPage
            ? `<a href="${pageHref}" class="card-img-link">${imgEl}</a>`
            : imgEl;
        const imgBlock = `<div class="card-img-wrap">${imgAnchored}${kuulaBadge}${videoBadge}</div>`;
        const titleBlock = hasPage
            ? `<h3><a href="${pageHref}" class="card-title-link">${y.name}</a></h3>`
            : `<h3>${y.name}</h3>`;
        const primaryHref = hasPage ? pageHref : inquireHref;

        return `
            <div class="card">
                ${imgBlock}
                <div class="card-body">
                    ${titleBlock}
                    <p>${y.description}</p>
                    <div class="card-actions">
                        <a href="${primaryHref}" class="card-link">${hasPage ? 'View Listing' : 'Inquire'}</a>
                        ${pdfLink}
                        ${kuulaLink}
                        ${videoLink}
                    </div>
                    <a href="tel:5618171547" class="card-call">Call Clark: 561-817-1547</a>
                </div>
            </div>
        `;
    }).join('');
}

document.addEventListener('DOMContentLoaded', () => {
    renderFeaturedYachts('featured-yachts-grid');
});
