// ===== Featured Yachts - single source of truth =====
// Generated by /admin/featured-yachts.html - Featured Image Maintenance
// You can also edit this file manually if preferred.
//
// Schema per entry:
//   image       - relative path to hero image (e.g. images/yachts/featured/foo.jpg)
//   name        - display title shown above the description
//   description - body copy under the title
//   link        - destination URL for the primary "Inquire" button (usually contact.html)
//   linkText    - label for the primary button
//   pdf         - optional. Relative path to a Full Details PDF in documents/yachts/featured/
//                 OR an absolute URL to an externally hosted spec sheet. Empty/missing = button hidden.
//   kuula       - optional. Sanitized <iframe> embed code for a Kuula 360 tour. Must point at
//                 kuula.co. Empty/missing = no 360 section, no badge.
//   page        - optional. Relative path to a dedicated listing page (e.g. yachts/fringe-benefits.html).
//                 When present, the card image + title + primary action link to this page.
//                 Empty/missing = primary action is the standard mailto Inquire.

const featuredYachts = [
    {
        image: "images/yachts/featured/sangaris.jpg",
        name: "1995 Manta 42 Mark II - SANGARIS $259,000.00",
        description: "Sangaris is a well equipped Blue Water Cruiser. She completed a refit in 2025 with new Volvo D1-30 Engines, New Generator, New Salon AC, New Refrigeration, New Windless, New Solar, New Mainsail Track, and so much more. This is a must see boat!",
        link: "contact.html",
        linkText: "Inquire",
        pdf: "documents/yachts/featured/2005-manta-42-mkii.pdf",
        kuula: "",
        page: ""
    },
    {
        image: "images/yachts/featured/riviera545suv.jpg",
        name: "2020 Riviera 545 SUV, \"Fringe Benefits\" $1,495,000",
        description: "The Riviera 545 SUV blends luxury cruising with adventure-ready capability. Three staterooms, a full-beam master, an expansive cockpit, and the signature Riviera build quality make her ideal for extended family voyages and weekend getaways alike.",
        link: "contact.html",
        linkText: "Inquire",
        pdf: "documents/yachts/featured/2020-riviera-545-suv.pdf",
        kuula: "<iframe src=\"https://kuula.co/share/collection/7MBqZ?logo=1&info=0&logosize=190&fs=1&vr=1&zoom=1&thumbs=3\" frameborder=\"0\" allow=\"xr-spatial-tracking; gyroscope; accelerometer\" allowfullscreen ></iframe>",
        page: "yachts/fringe-benefits.html"
    },
    {
        image: "images/yachts/featured/southern-wind.jpg",
        name: "1991 Southern Wind 72, \"Fortunato\" - $435,000",
        description: "Because of their renowned build quality and Bruce Farr’s exceptional design, the Southern Wind 72 is equally at home crossing oceans, effortlessly clicking off 200‑mile days or competing in long‑distance racing!",
        link: "contact.html",
        linkText: "Inquire",
        pdf: "documents/yachts/featured/1991-southern-wind-bruce-farr-fast-72.pdf",
        kuula: "",
        page: ""
    },
    {
        image: "images/yachts/featured/riviera-465suv.jpg",
        name: "2024 Riviera 465 SUV - $1,574,000",
        description: "Picture life on board your brilliant new Riviera SUV adventure yacht, surrounded in luxury, totally relaxed and taking every opportunity to create precious memories your friends and loved ones.",
        link: "contact.html",
        linkText: "Inquire",
        pdf: "documents/yachts/featured/2024-riviera-465-suv.pdf",
        kuula: "",
        page: ""
    },
    {
        image: "images/yachts/featured/2022 Sunseeker 68 Manhattan",
        name: "2022 Sunseeker 68 Manhattan",
        description: "This 2022 Sunseeker 68 Manhattan represents a rare opportunity to acquire the only 4 cabin layout currently availableon the market. Well maintained with approximately 900 hours on the MAN V8 1200 engines and full service records up to date.",
        link: "contact.html",
        linkText: "Inquire",
        pdf: "documents/yachts/featured/2022-sunseeker-manhattan_68.pdf",
        kuula: "",
        page: ""
    },
    {
        image: "images/yachts/featured/2018-absolute-60-fly.jpg",
        name: "2018 Absolute 60 Fly",
        description: "Introducing Mama’s House, a beautifully maintained 2018 Absolute 60 FLY that perfectly blends Italian design,performance, and comfort. Powered by twin Volvo Penta D11 IPS 950s with approximately 550 hours, she offers smooth, efficient cruising.",
        link: "contact.html",
        linkText: "Inquire",
        pdf: "documents/yachts/featured/2018-absolute-60-fly.pdf",
        kuula: "",
        page: ""
    }
];

function isFilledYacht(y) {
    // A slot counts as "filled" if it has either an image, or a real (non-placeholder) name.
    if (y.image && y.image.trim()) return true;
    if (y.name && y.name !== 'Featured Listing') return true;
    return false;
}

// Strip the price portion from a yacht name so the email subject is clean.
// "1995 Manta 42 Mark II - SANGARIS $259,000.00" -> "1995 Manta 42 Mark II - SANGARIS"
function _fyStripPrice(name) {
    return (name || '').replace(/[\s,\-]*\$[\d,\.]+.*$/, '').trim();
}
function _fyInquireMailto(name) {
    const subject = encodeURIComponent(_fyStripPrice(name) + ' Inquiry');
    return `mailto:clark@haleyyachts.com?subject=${subject}`;
}

// Re-sanitize the stored Kuula iframe at render time as a defense-in-depth check.
// Admin already sanitizes on save; this also rejects any hand-edited entries that
// don't point at kuula.co.
function _fySanitizeKuula(raw) {
    if (!raw || !raw.trim()) return '';
    const tagStart = raw.match(/<iframe\b[^>]*>/i);
    if (!tagStart) return '';
    const openTag = tagStart[0];
    const srcMatch = openTag.match(/\bsrc\s*=\s*(['"])(.*?)\1/i);
    if (!srcMatch) return '';
    const src = srcMatch[2];
    if (!/(^|\/\/|\.)kuula\.co(\/|$)/i.test(src)) {
        console.warn('[Kuula] Rejected iframe at render: src is not kuula.co ->', src);
        return '';
    }
    const allowed = ['src','width','height','frameborder','allow','allowfullscreen','style'];
    const attrs = {};
    const attrRe = /(\w[\w-]*)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'>]+))|(\ballowfullscreen\b)/gi;
    let m;
    while ((m = attrRe.exec(openTag)) !== null) {
        if (m[5]) { attrs['allowfullscreen'] = ''; continue; }
        const name = m[1].toLowerCase();
        if (!allowed.includes(name)) continue;
        attrs[name] = m[2] !== undefined ? m[2] : (m[3] !== undefined ? m[3] : (m[4] || ''));
    }
    const parts = ['<iframe'];
    for (const k of allowed) {
        if (!(k in attrs)) continue;
        if (k === 'allowfullscreen') { parts.push('allowfullscreen'); continue; }
        const v = String(attrs[k]).replace(/"/g, '&quot;');
        parts.push(`${k}="${v}"`);
    }
    parts.push('></iframe>');
    return parts.join(' ');
}

// Inject the 360 CSS + modal scaffold once. Card grid renders many times;
// styles + modal markup inject once and are reused for every card.
function _fyInjectKuulaStyles() {
    if (document.getElementById('fy-kuula-styles')) return;
    const css = `
.card .card-img { position: relative; }
.fy-kuula-badge {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    background: rgba(10, 22, 40, 0.88);
    color: #fff;
    font-size: 0.72rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 1.2px;
    padding: 7px 12px;
    border-radius: 3px;
    border: 1px solid rgba(33, 203, 234, 0.55);
    cursor: pointer;
    position: absolute;
    top: 12px;
    right: 12px;
    z-index: 2;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.25);
    transition: background 0.2s, transform 0.2s, border-color 0.2s;
}
.fy-kuula-badge:hover,
.fy-kuula-badge:focus-visible {
    background: #21cbea;
    border-color: #21cbea;
    transform: translateY(-1px);
    outline: none;
}
.fy-kuula-badge::before {
    content: '\\25F0';
    font-size: 0.95rem;
    line-height: 1;
}
.fy-kuula-link {
    background: none;
    border: none;
    padding: 0;
    font: inherit;
    cursor: pointer;
    font-size: 0.82rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: #21cbea;
}
.fy-kuula-link:hover { color: #1aa8c4; }
.fy-kuula-link::after { content: ' \\2192'; transition: margin-left 0.2s; }
.fy-kuula-link:hover::after { margin-left: 4px; }

.fy-kuula-modal {
    position: fixed;
    inset: 0;
    background: rgba(5, 12, 24, 0.92);
    z-index: 10000;
    display: none;
    align-items: center;
    justify-content: center;
    padding: 24px;
}
.fy-kuula-modal.is-open { display: flex; }
.fy-kuula-modal-inner {
    position: relative;
    width: 100%;
    max-width: 1280px;
    aspect-ratio: 16 / 9;
    max-height: calc(100vh - 48px);
    background: #000;
    border-radius: 4px;
    overflow: hidden;
    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.55);
}
.fy-kuula-modal-inner iframe {
    width: 100%;
    height: 100%;
    border: 0;
    display: block;
}
.fy-kuula-modal-title {
    position: absolute;
    top: 14px;
    left: 18px;
    color: #fff;
    font-size: 0.82rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 1.5px;
    background: rgba(10, 22, 40, 0.75);
    padding: 6px 12px;
    border-radius: 3px;
    z-index: 1;
    pointer-events: none;
    max-width: calc(100% - 80px);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
.fy-kuula-modal-close {
    position: absolute;
    top: 10px;
    right: 10px;
    width: 40px;
    height: 40px;
    border-radius: 50%;
    border: none;
    background: rgba(10, 22, 40, 0.85);
    color: #fff;
    font-size: 1.4rem;
    line-height: 1;
    cursor: pointer;
    z-index: 2;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: background 0.2s;
}
.fy-kuula-modal-close:hover,
.fy-kuula-modal-close:focus-visible {
    background: #21cbea;
    outline: none;
}
@media (max-width: 600px) {
    .fy-kuula-modal { padding: 0; }
    .fy-kuula-modal-inner { border-radius: 0; max-height: 100vh; aspect-ratio: auto; height: 100vh; }
    .fy-kuula-badge { font-size: 0.66rem; padding: 6px 10px; }
}
`;
    const style = document.createElement('style');
    style.id = 'fy-kuula-styles';
    style.textContent = css;
    document.head.appendChild(style);

    // Build the single shared modal once.
    if (!document.getElementById('fy-kuula-modal')) {
        const modal = document.createElement('div');
        modal.id = 'fy-kuula-modal';
        modal.className = 'fy-kuula-modal';
        modal.setAttribute('role', 'dialog');
        modal.setAttribute('aria-modal', 'true');
        modal.setAttribute('aria-label', '360 walkthrough');
        modal.innerHTML = `
            <div class="fy-kuula-modal-inner">
                <div class="fy-kuula-modal-title" id="fy-kuula-modal-title"></div>
                <button type="button" class="fy-kuula-modal-close" aria-label="Close 360 walkthrough">&times;</button>
                <div class="fy-kuula-modal-frame"></div>
            </div>
        `;
        document.body.appendChild(modal);

        // Close on backdrop click, close button, or Escape.
        modal.addEventListener('click', (e) => {
            if (e.target === modal || e.target.closest('.fy-kuula-modal-close')) {
                _fyCloseKuula();
            }
        });
        document.addEventListener('keydown', (e) => {
            if (e.key === 'Escape' && modal.classList.contains('is-open')) {
                _fyCloseKuula();
            }
        });
    }
}

// Open the shared lightbox with the iframe HTML stashed on the trigger element.
// Iframe HTML lives on a data attribute so we don't depend on any DOM structure
// inside the card.
function _fyOpenKuula(trigger) {
    const modal = document.getElementById('fy-kuula-modal');
    if (!modal) return;
    const iframeHtml = trigger.getAttribute('data-kuula');
    const title = trigger.getAttribute('data-kuula-title') || '360 Walkthrough';
    if (!iframeHtml) return;
    modal.querySelector('.fy-kuula-modal-frame').innerHTML = iframeHtml;
    modal.querySelector('#fy-kuula-modal-title').textContent = title;
    modal.classList.add('is-open');
    document.body.style.overflow = 'hidden';
    const closeBtn = modal.querySelector('.fy-kuula-modal-close');
    if (closeBtn) closeBtn.focus();
}

function _fyCloseKuula() {
    const modal = document.getElementById('fy-kuula-modal');
    if (!modal) return;
    modal.classList.remove('is-open');
    // Wipe the iframe to stop audio/loading.
    modal.querySelector('.fy-kuula-modal-frame').innerHTML = '';
    document.body.style.overflow = '';
}

// HTML-escape a string for safe insertion into a data-* attribute.
function _fyEscapeAttr(s) {
    return String(s)
        .replace(/&/g, '&amp;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
}

function renderFeaturedYachts(containerId) {
    const container = document.getElementById(containerId);
    if (!container) return;

    _fyInjectKuulaStyles();

    container.innerHTML = featuredYachts.filter(isFilledYacht).map(y => {
        const imgStyle = y.image
            ? `background-image: url('${y.image}'); background-size: cover; background-position: center;`
            : '';
        const imgLabel = y.image ? '' : 'Featured Yacht Image';
        const pdfLink = (y.pdf && y.pdf.trim())
            ? `<a href="${y.pdf}" class="card-link card-link-secondary" target="_blank" rel="noopener">Spec Sheet (PDF)</a>`
            : '';
        const inquireHref = _fyInquireMailto(y.name);
        const kuulaClean = _fySanitizeKuula(y.kuula);
        const kuulaTitle = _fyStripPrice(y.name) + ' - 360 Walkthrough';
        const kuulaDataAttr = kuulaClean
            ? ` data-kuula="${_fyEscapeAttr(kuulaClean)}" data-kuula-title="${_fyEscapeAttr(kuulaTitle)}"`
            : '';
        // Badge click must not bubble up to the surrounding image anchor (when
        // a card has both a 360 badge and a `page` link wrapping the image).
        const kuulaBadge = kuulaClean
            ? `<button type="button" class="fy-kuula-badge" aria-label="Open 360 walkthrough"${kuulaDataAttr} onclick="event.stopPropagation(); _fyOpenKuula(this)">360&deg; Tour</button>`
            : '';
        const kuulaLink = kuulaClean
            ? `<button type="button" class="fy-kuula-link" aria-label="Open 360 walkthrough"${kuulaDataAttr} onclick="_fyOpenKuula(this)">View 360&deg; Tour</button>`
            : '';

        // If a dedicated listing page exists, image + title + primary action
        // all point at it. Otherwise the image and title are plain (no anchor)
        // and the primary action falls back to the standard mailto Inquire.
        const hasPage = !!(y.page && y.page.trim());
        const pageHref = hasPage ? y.page : '';
        const imgInner = `${imgLabel}${kuulaBadge}`;
        const imgBlock = hasPage
            ? `<a href="${pageHref}" class="card-img-link"><div class="card-img" style="${imgStyle}">${imgInner}</div></a>`
            : `<div class="card-img" style="${imgStyle}">${imgInner}</div>`;
        const titleBlock = hasPage
            ? `<h3><a href="${pageHref}" class="card-title-link">${y.name}</a></h3>`
            : `<h3>${y.name}</h3>`;
        const primaryHref = hasPage ? pageHref : inquireHref;

        return `
            <div class="card">
                ${imgBlock}
                <div class="card-body">
                    ${titleBlock}
                    <p>${y.description}</p>
                    <div class="card-actions">
                        <a href="${primaryHref}" class="card-link">${hasPage ? 'View Listing' : 'Inquire'}</a>
                        ${pdfLink}
                        ${kuulaLink}
                    </div>
                    <a href="tel:5618171547" class="card-call">Call Clark: 561-817-1547</a>
                </div>
            </div>
        `;
    }).join('');
}

document.addEventListener('DOMContentLoaded', () => {
    renderFeaturedYachts('featured-yachts-grid');
});
