---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zbbs3q9g44rj/public_html/owyg
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/cp -R vendors/. "$DEPLOYPATH/"
    - /bin/find "$DEPLOYPATH" -type d -exec /bin/chmod 755 {} +
    - /bin/find "$DEPLOYPATH" -type f -exec /bin/chmod 644 {} +
