// ===== Published Articles - single source of truth =====
// Generated by /admin/article-manager.html - Article Manager

const publishedArticles = [
    {
        "type": "industry-news",
        "title": "Sunseeker gets a new permanent CEO",
        "excerpt": "Sunseeker completed the sale of the company to investment group. New owners first objective? Hire a new and permanent CEO",
        "date": "2026-04-03",
        "author": "Clark Haley",
        "slug": "sunseeker-gets-a-new-permanent-ceo",
        "fileName": "2026-04-03-sunseeker-gets-a-new-permanent-ceo.html",
        "heroImage": "sunseekerceo.jpg",
        "keywords": "Sunseeker Yachts, Denison Yachts, One Water Yacht Group, Clark Haley, Yacht Broker"
    }
];
