#!/usr/bin/env python3
"""
Patch an asking price inside an OWYG-generated brochure PDF, in place.

The One Water listing system renders the price as real text (a Type3 font), not
as part of the photo, so a price reduction can be corrected in the existing PDF
without waiting on a regenerated brochure. This script redacts every occurrence
of the old price and redraws the new one at the identical position and size, in
Helvetica-Bold, using the ink color sampled from the original glyphs.

    python3 scripts/patch-pdf-price.py <pdf> <old-price> <new-price> [--dry-run]

    python3 scripts/patch-pdf-price.py \
        documents/yachts/1991-southern-wind-72-fortunato.pdf \
        '$395,000' '$329,000'

Requires PyMuPDF (pip install pymupdf).

Two cautions:
  - The brochure is generated by OWYG. Update the price in THEIR system too, or
    the next regeneration silently reverts this patch and the syndicated feeds
    (YachtWorld, the MLS) keep showing the old number.
  - Prices of a different digit count can reflow the header line. The script
    warns when the redrawn width differs meaningfully from the original.
"""

import os
import sys
import fitz

INK_SAMPLE_DPI = 300
WIDTH_WARN_PT = 2.0


def sample_ink(page, bbox):
    """Darkest pixel inside the glyph box - the text color, not the background."""
    pm = page.get_pixmap(dpi=INK_SAMPLE_DPI)
    z = INK_SAMPLE_DPI / 72
    x0, y0, x1, y1 = (int(v * z) for v in bbox)
    px = min(
        (pm.pixel(x, y)
         for y in range(y0, min(y1, pm.height))
         for x in range(x0, min(x1, pm.width))),
        key=sum,
    )
    return tuple(c / 255 for c in px)


def main():
    args = [a for a in sys.argv[1:] if a != "--dry-run"]
    dry = "--dry-run" in sys.argv
    if len(args) != 3:
        print(__doc__)
        return 2
    path, old, new = args

    doc = fitz.open(path)
    total = 0

    for pno, page in enumerate(doc):
        spans = [s
                 for b in page.get_text("dict")["blocks"]
                 for l in b.get("lines", [])
                 for s in l["spans"]
                 if s["text"].strip() == old]
        if not spans:
            continue

        marks = []
        for s in spans:
            ink = sample_ink(page, s["bbox"])
            marks.append((s["origin"], s["size"], ink, s["bbox"]))
            print(f"  page {pno + 1}: {old} @ {s['size']}pt "
                  f"ink rgb{tuple(round(c * 255) for c in ink)}")

        if dry:
            total += len(spans)
            continue

        for s in spans:
            page.add_redact_annot(fitz.Rect(s["bbox"]) + (-1, -1, 1, 1), fill=(1, 1, 1))
        page.apply_redactions()

        for origin, size, ink, bbox in marks:
            page.insert_text(origin, new, fontname="hebo", fontsize=size, color=ink)
            was = bbox[2] - bbox[0]
            now = fitz.get_text_length(new, fontname="hebo", fontsize=size)
            if abs(now - was) > WIDTH_WARN_PT:
                print(f"  WARNING page {pno + 1}: width {was:.1f}pt -> {now:.1f}pt "
                      f"- check the layout did not reflow")
            total += 1

    if total == 0:
        print(f"No occurrences of {old} found in {path}")
        return 1

    if dry:
        print(f"[dry run] would replace {total} occurrence(s)")
        return 0

    # PyMuPDF refuses a non-incremental save over the open original, so write a
    # sibling temp file and move it into place once it is fully written.
    tmp = path + ".tmp"
    doc.save(tmp, garbage=3, deflate=True)
    doc.close()
    os.replace(tmp, path)

    check = fitz.open(path)
    left = [i + 1 for i, p in enumerate(check) if old in (p.get_text() or "")]
    print(f"Replaced {total} occurrence(s) in {path}")
    print(f"Pages: {len(check)}   remaining '{old}': {left or 'none'}")
    print("Now open page 1 and confirm it looks right before committing.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
