// ===== Published Articles - single source of truth =====
// Generated by /admin/article-manager.html - Article Manager
// You can also edit this file manually if preferred.

const publishedArticles = [
    {
        "type": "travel",
        "title": "Cruising the Exuma Cays Land and Sea Park: What We Get for Our Trouble",
        "excerpt": "Years ago my family sailed our boat through the Exuma Cays Land and Sea Park, the Bahamas, and the place never let go of me. Here is what makes Shroud Cay, Warderick Wells, and Pipe Creek worth every mile it takes to get there, from a captain who has actually run these waters.",
        "date": "2026-06-16",
        "author": "Clark Haley",
        "slug": "cruising-the-exuma-cays-land-and-sea-park-what-we-get-for-ou",
        "fileName": "2026-06-16-cruising-the-exuma-cays-land-and-sea-park-what-we-get-for-ou.html",
        "heroImage": "dsc02299.jpg",
        "keywords": "Exuma Cays Land and Sea Park, cruising the Exumas, Warderick Wells anchorage, Shroud Cay, Pipe Creek Bahamas, Bahamas cruising with dogs, Exumas by boat, no-take marine reserve Bahamas, Bahamas anchorages, Haley Yachts"
    },
    {
        "type": "newsletters",
        "title": "The Logbook | June 2026",
        "excerpt": "The June issue of The Logbook: a note from Clark on the OWYG Bahamas Rendezvous (July 16-19, Freeport), featured listings (Riviera 545 Fringe Benefits, Southern Wind 72 Fortunato, Offshore 48 Island Girl), Bahamas-bound reading, and recent sales.",
        "date": "2026-06-16",
        "author": "Clark Haley",
        "slug": "the-logbook-june-2026",
        "fileName": "2026-06-16-the-logbook-june-2026.html",
        "heroImage": "logbook-2026-06-hero.jpg",
        "keywords": "Haley Yachts newsletter, The Logbook, June 2026, yacht broker newsletter, Clark Haley, Florida yacht broker, OWYG Bahamas Rendezvous, Riviera 545 SUV Fringe Benefits, Southern Wind 72 Fortunato, Offshore 48 Island Girl, Riviera 4300 Sports Express, Exuma Cays Land and Sea Park, Bahamas crossing, recent yacht sales"
    },
    {
        "type": "how-to",
        "title": "Boat Loans and Marine Financing, Explained",
        "excerpt": "Down payments, terms, rate ranges, and the paperwork lenders want, plus a straight look at cash versus finance at the yacht price point. Here is how marine financing actually works.",
        "date": "2026-06-11",
        "author": "Clark Haley",
        "slug": "boat-loans-and-marine-financing-explained",
        "fileName": "2026-06-11-boat-loans-and-marine-financing-explained.html",
        "heroImage": "dollar-signs.jpg",
        "keywords": "marine financing, boat loans, yacht financing, how to finance a yacht, boat loan down payment, yacht loan rates, marine lender requirements, financing a boat in Florida, Haley Yachts, One Water Yacht Group, OWYG"
    },
    {
        "type": "boat-reviews",
        "title": "A First-Time Buyer's Guide to Riviera",
        "excerpt": "Riviera builds some of the most sought-after motor yachts on the water, but the lineup can be confusing the first time you look at it. Here is the Sport Yacht, SUV, and Motor Yacht ranges explained, and who each one fits.",
        "date": "2026-06-11",
        "author": "Clark Haley",
        "slug": "a-first-time-buyers-guide-to-riviera",
        "fileName": "2026-06-11-a-first-time-buyers-guide-to-riviera.html",
        "heroImage": "08-riviera-6200-sype-foredeck-3.jpg",
        "keywords": "Riviera yachts guide, Riviera for sale Florida, Riviera Sport Yacht, Riviera SUV, Riviera Motor Yacht, new Riviera dealer Florida, Riviera 4300 Sports Express, first time Riviera buyer, Haley Yachts"
    },
    {
        "type": "how-to",
        "title": "What a Survey Really Covers (and Why it Protects You)",
        "excerpt": "A marine survey is the single best money you spend before buying a yacht. Here is what a pre-purchase survey actually covers, how the sea trial and haul-out fit in, and how the findings turn into real negotiating leverage.",
        "date": "2026-06-06",
        "author": "Clark Haley",
        "slug": "what-a-survey-really-covers-and-why-it-protects-you",
        "fileName": "2026-06-06-what-a-survey-really-covers-and-why-it-protects-you.html",
        "heroImage": "survey-1st-hero-image.jpeg",
        "keywords": "pre-purchase boat survey, yacht survey, marine survey, marine survey before buying a boat, boat survey cost, pre-purchase vs insurance survey, boat sea trial, yacht haul-out inspection, marine engine survey, used yacht inspection, hiring a marine surveyor, what does a boat survey cover"
    },
    {
        "type": "how-to",
        "title": "How to Sell Your Yacht",
        "excerpt": "Excerpt / meta description: Getting the best price for your yacht is not luck. It comes down to pricing to today's market, prepping the boat before it lists, and presenting it with photography, video, and a 360 tour that make a buyer want to step abo",
        "date": "2026-06-06",
        "author": "Clark Haley",
        "slug": "how-to-sell-your-yacht",
        "fileName": "2026-06-06-how-to-sell-your-yacht.html",
        "heroImage": "how-to-sell-your-yacht---heroimage.jpeg",
        "keywords": "how to sell my yacht, sell my boat fast, selling a yacht in Florida, yacht broker, free yacht market analysis, how to price a yacht to sell, boat listing photography, yacht listing video walkthrough, 360 virtual boat tour, prepping a boat to sell, yacht service records and paperwork, what is my boat worth, get top dollar for your yacht, list my yacht for sale"
    },
    {
        "type": "boat-reviews",
        "title": "Riviera 4300 Sports Express: The Day Boat That Knows How to Stay the Weekend",
        "excerpt": "The Riviera 4300 Sports Express handles a Florida Saturday and a Bahamas weekend with equal ease. Haley Yachts has a new 4300 arriving in July, straight from Riviera, and it will not last long.",
        "date": "2026-06-06",
        "author": "Clark Haley",
        "slug": "riviera-4300-sports-express-the-day-boat-that-knows-how-to-s",
        "fileName": "2026-06-06-riviera-4300-sports-express-the-day-boat-that-knows-how-to-s.html",
        "heroImage": "swimplatform-riv4300.jpg",
        "keywords": "Riviera 4300 Sports Express, Riviera Sports Express for sale Florida, Volvo Penta IPS, joystick docking, Bahamas weekender, Florida day boat, luxury express cruiser, Haley Yachts, new Riviera for sale"
    },
    {
        "type": "travel",
        "title": "Provisioning and Prepping for a Crossing to the Bahamas",
        "excerpt": "The Bahamas are close enough to see on a clear day and far enough to demand real preparation. Here is how to plan fuel and reserves, handle documents and customs, and pick the weather window for a safe crossing from Florida.",
        "date": "2026-06-06",
        "author": "Clark Haley",
        "slug": "provisioning-and-prepping-for-a-crossing-to-the-bahamas",
        "fileName": "2026-06-06-provisioning-and-prepping-for-a-crossing-to-the-bahamas.html",
        "heroImage": "bahamascrossing.jpg",
        "keywords": "crossing to the Bahamas by boat, Florida to Bahamas crossing, Gulf Stream crossing, Bahamas customs and immigration, Bahamas cruising permit, fuel range planning Bahamas, provisioning for a Bahamas trip, weather window Gulf Stream, Haley Yachts"
    },
    {
        "type": "industry-news",
        "title": "One Water Announces \"OWYG Bahamas Rendezvous\" July 16-19, 2026",
        "excerpt": "The annual Summer Rendezvous will bring together owners and guests aboard Sunseeker, Riviera, Absolute, and HCB yachts for four unforgettable days of cruising, dockside hospitality, beach club experiences, island excursions, and curated social events",
        "date": "2026-06-04",
        "author": "Clark Haley",
        "slug": "one-water-announces-owyg-bahamas-rendezvous-july-16-19-2026",
        "fileName": "2026-06-04-one-water-announces-owyg-bahamas-rendezvous-july-16-19-2026.html",
        "heroImage": "hero1.png",
        "keywords": "Riviera Yachts, HCB CenterConsoles, Sunseeker Yachts, OneWater Yacht Group, HaleyYachts, Bahamas, Grand Bahama Yacht Club"
    },
    {
        "type": "newsletters",
        "title": "The Logbook | May 2026",
        "excerpt": "The first issue of The Logbook: featured listings (Riviera 545, Manta 42 Sangaris, Southern Wind 72), industry news, recent sales, and a note from Clark on his first fast-cruiser run to the Abacos.",
        "date": "2026-05-09",
        "author": "Clark Haley",
        "slug": "the-logbook-may-2026",
        "fileName": "2026-05-09-the-logbook-may-2026.html",
        "heroImage": "logbook-2026-05-hero.jpg",
        "keywords": "Haley Yachts newsletter, The Logbook, May 2026, yacht broker newsletter, Clark Haley, Florida yacht broker, Riviera 545 SUV, Manta 42 Sangaris, Southern Wind 72 Fortunato, Abacos cruising, Ted Turner sailing, Riviera solar, Bahamas cruise, recent yacht sales"
    },
    {
        "type": "how-to",
        "title": "How to Plan Your First Bahamas Cruise",
        "excerpt": "The Bahamas is closer than most first-time cruisers think, and the prep is more straightforward than the dock talk suggests. Here's the routine I run on ROAM before every crossing - boat, provisions, weather, customs.",
        "date": "2026-05-09",
        "author": "Clark Haley",
        "slug": "how-to-plan-your-first-bahamas-cruise",
        "fileName": "2026-05-09-how-to-plan-your-first-bahamas-cruise.html",
        "heroImage": "conch-blow.jpg",
        "keywords": "Bahamas cruise, first Bahamas cruise, cruising the Abacos, Abacos cruising guide, Bahamas crossing from Florida, first-time cruiser, yacht provisioning, boat preparation Bahamas, CLICK2CLEAR Bahamas customs, Bahamas weather windows, Gulf Stream crossing, Marsh Harbour, Florida yacht broker, Clark Haley, Haley Yachts"
    },
    {
        "type": "industry-news",
        "title": "We Lost a Yachting Giant",
        "excerpt": "Ted Turner is gone. Most will remember the media mogul. Sailors will remember the amateur skipper who swept Courageous 4-0 at the 1977 America's Cup, won 500 trophies, and brought swagger to a sport that needed it. Fair winds, Captain.",
        "date": "2026-05-09",
        "author": "Clark Haley",
        "slug": "we-lost-a-yachting-giant",
        "fileName": "2026-05-09-we-lost-a-yachting-giant.html",
        "heroImage": "ted-turner-3.jpg",
        "keywords": "Ted Turner, Ted Turner sailing, Captain Outrageous, 1977 America's Cup, Courageous yacht, America's Cup history, competitive sailing, Yachtsman of the Year, Fastnet Race 1979, Sydney to Hobart, sailing legend, sailing tribute, Clark Haley, Haley Yachts, Florida yacht broker"
    },
    {
        "type": "industry-news",
        "title": "Riviera Unveils Integrated Solar Breakthrough",
        "excerpt": "Riviera is bonding a 2mm nano-composite solar skin directly into the hardtop during construction. Real boats are pulling 10kWh a day and running three days off-grid. Available on new builds 39 to 78 feet, with retrofits through Riviera Aftermarket.",
        "date": "2026-05-08",
        "author": "Clark Haley",
        "slug": "riviera-unveils-integrated-solar-breakthrough",
        "fileName": "2026-05-08-riviera-unveils-integrated-solar-breakthrough.html",
        "heroImage": "praxis-solar3.jpg",
        "keywords": "Riviera yachts, Praxis solar, integrated solar yacht, nano-composite solar, marine solar power, lithium iron phosphate, off-grid cruising, generator-free yacht, yacht broker Florida, Haley Yachts, Clark Haley, luxury motor yacht, Riviera Aftermarket retrofit"
    },
    {
        "type": "travel",
        "title": "Bahamas Cruising Permit Changes - April 2026",
        "excerpt": "Bahamas cruising permit fees changed again - effective April 1, 2026. If you're yacht shopping with the Bahamas on your radar, these new costs are part of the ownership conversation. Here's what you need to know.",
        "date": "2026-05-05",
        "author": "Clark Haley",
        "slug": "bahamas-cruising-permit-changes-april-2026",
        "fileName": "2026-05-05-bahamas-cruising-permit-changes-april-2026.html",
        "heroImage": "bahamascrusingpermits.jpg",
        "keywords": "Bahamas cruising permit 2026, Bahamas cruising fees updated, how much does it cost to cruise the Bahamas, Bahamas boat permit Florida, yacht cruising Bahamas from Florida, Bahamas FDCC permit, yacht broker Bahamas cruising advice, Palm Beach yacht broker"
    },
    {
        "type": "industry-news",
        "title": "Eight Sunseeker Yachts Find New Owners at Fort Lauderdale International Boat Show 2025",
        "excerpt": "Eight Sunseeker yachts sold at FLIBS - including a Predator 75, 95 Yacht, and three Manhattan 55s. Strong demand, great energy at the show. If Sunseeker is on your radar, let's talk.",
        "date": "2026-05-05",
        "author": "Clark Haley",
        "slug": "eight-sunseeker-yachts-find-new-owners-at-fort-lauderdale-in",
        "fileName": "2026-05-05-eight-sunseeker-yachts-find-new-owners-at-fort-lauderdale-in.html",
        "heroImage": "sunseekerflbs.jpg",
        "keywords": "Sunseeker yachts for sale, Sunseeker Fort Lauderdale boat show, Sunseeker Manhattan 55, Sunseeker Predator 75, Sunseeker 95 Yacht, Fort Lauderdale International Boat Show 2025, luxury yacht dealer Florida, One Water Yacht Group Sunseeker"
    },
    {
        "type": "industry-news",
        "title": "West Marine Readies Possible Bankruptcy",
        "excerpt": "West Marine is preparing for a possible Chapter 11 bankruptcy and store closures. For yacht owners and buyers, it's a good reminder to work with trusted marine professionals for your boating needs.",
        "date": "2026-05-05",
        "author": "Reshmi Basu",
        "slug": "west-marine-readies-possible-bankruptcy",
        "fileName": "2026-05-05-west-marine-readies-possible-bankruptcy.html",
        "heroImage": "west-marine.jpg",
        "keywords": "West Marine bankruptcy 2026, West Marine store closures, boating supply store closing, marine industry news, yacht broker Palm Beach, boating resources Florida, yacht ownership advice"
    },
    {
        "type": "how-to",
        "title": "How to Choose a Yacht Broker",
        "excerpt": "Choosing the right yacht broker can make or break the deal. Know what to look for, what questions to ask, and the red flags that should send you elsewhere.",
        "date": "2026-05-05",
        "author": "Clark Haley",
        "slug": "how-to-choose-a-yacht-broker",
        "fileName": "2026-05-05-how-to-choose-a-yacht-broker.html",
        "heroImage": "clark-square-lean-crop-with-background.jpg",
        "keywords": "how to choose a yacht broker, yacht broker Florida, licensed yacht broker, IYBA member broker, buying a yacht Florida, selling a yacht Florida, yacht broker Palm Beach, yacht broker Jupiter FL"
    },
    {
        "type": "boat-reviews",
        "title": "World Premiere - Riviera 6200 Sport Yacht",
        "excerpt": "Riviera's new 6200 Sport Yacht delivers big-boat living in 62 feet - full-beam master, alfresco aft deck, gourmet galley, and twin Volvo Penta 900hp IPS drives. This one is built to cruise in serious style.",
        "date": "2026-05-04",
        "author": "Clark Haley",
        "slug": "world-premiere-riviera-6200-sport-yacht",
        "fileName": "2026-05-04-world-premiere-riviera-6200-sport-yacht.html",
        "heroImage": "01-riviera-6200-sport-yacht-platinum-edition-running-02.jpg",
        "keywords": "Riviera, Sport Yacht, Motor Yacht"
    },
    {
        "type": "travel",
        "title": "A Simple Trip to the Abacos",
        "excerpt": "Somewhere between the third anchorage and the first genuine sunset, you realize what you left behind on the mainland doesn't matter nearly as much as you thought. A week in the Abacos has a way of stripping the noise and showing you what does.",
        "date": "2026-05-02",
        "author": "Clark Haley",
        "slug": "a-simple-trip-to-the-abacos",
        "fileName": "2026-05-02-a-simple-trip-to-the-abacos.html",
        "heroImage": "dsc02094.jpg",
        "keywords": "Abacos, Bahamas cruising, Marsh Harbour, Man O' War Cay, Exumas, yacht travel, boat life, slow living, anchorage, cruising lifestyle, Bahamas yacht charter, captain's perspective, Clark Haley, Haley Yachts, why people buy boats"
    },
    {
        "type": "industry-news",
        "title": "Sunseeker gets a new permanent CEO",
        "excerpt": "Sunseeker completed the sale of the company to investment group. New owners first objective? Hire a new and permanent CEO",
        "date": "2026-04-03",
        "author": "Clark Haley",
        "slug": "sunseeker-gets-a-new-permanent-ceo",
        "fileName": "2026-04-03-sunseeker-gets-a-new-permanent-ceo.html",
        "heroImage": "sunseekerceo.jpg",
        "keywords": "Sunseeker Yachts, Sunseeker CEO, Sunseeker Yachts news, Sunseeker leadership, One Water Yacht Group, OWYG, Sunseeker acquisition, Sunseeker dealer network, Sunseeker yachts for sale, Sunseeker yacht broker Florida, luxury yacht news, Clark Haley, Haley Yachts"
    }
];

var CATEGORY_META = {
    'boat-reviews':  { tag: 'Boat Review',   label: 'Boat Reviews' },
    'newsletters':   { tag: 'Newsletter',    label: 'Newsletters' },
    'how-to':        { tag: 'How To',        label: 'How To' },
    'travel':        { tag: 'Travel',        label: 'Travel' },
    'industry-news': { tag: 'Industry News', label: 'Industry News' }
};

function getActiveCategories() {
    var chips = document.querySelectorAll('.filter-chip[data-category]');
    if (!chips.length) {
        // No chip UI on this page - treat all categories as active.
        return Object.keys(CATEGORY_META);
    }
    // Single-select model: find the one active chip. The "all" chip means every
    // category; any real category chip means just that one. Default is "all".
    var selected = null;
    chips.forEach(function(c) {
        if (c.classList.contains('active')) selected = c.dataset.category;
    });
    if (!selected || selected === 'all') return Object.keys(CATEGORY_META);
    return [selected];
}

// Escape a string for safe insertion into HTML text (used for the search query
// echoed back in the empty-state message).
function escapeHtml(str) {
    return String(str)
        .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

// Build the searchable haystack for one article: title + excerpt + keywords +
// author + the category tag/label (so "boat review" or "travel" matches too).
function articleHaystack(a) {
    var meta = CATEGORY_META[a.type] || {};
    return [
        a.title, a.excerpt, a.keywords, a.author,
        a.type, meta.tag, meta.label
    ].join(' ').toLowerCase();
}

// Multi-word AND match: every whitespace-separated term must appear somewhere
// in the haystack. Empty query matches everything.
function matchesQuery(haystack, terms) {
    for (var i = 0; i < terms.length; i++) {
        if (haystack.indexOf(terms[i]) === -1) return false;
    }
    return true;
}

function renderArticles(searchTerm) {
    var EMPTY_MESSAGE = '<p style="color:#999;font-style:italic;font-size:0.9rem;">No articles published yet. Check back soon.</p>';
    var NO_CATEGORIES = '<p style="color:#999;font-style:italic;font-size:0.9rem;">No categories selected. Click a category chip above to include it.</p>';
    var rawQuery = (searchTerm || '').replace(/\s+/g, ' ').trim();
    var query = rawQuery.toLowerCase();
    var terms = query ? query.split(' ') : [];
    var NO_RESULTS_SEARCH = '<p style="color:#999;font-style:italic;font-size:0.9rem;">No articles match "' + escapeHtml(rawQuery) + '".</p>';
    var activeCats = getActiveCategories();

    function buildCardHtml(article) {
        var meta = CATEGORY_META[article.type] || { tag: article.type };
        var date = new Date(article.date + 'T12:00:00');
        var displayDate = date.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
        var heroSrc = article.heroImage
            ? 'articles/' + article.type + '/images/' + article.heroImage
            : '';
        var articleUrl = 'articles/' + article.type + '/' + article.fileName;

        return '<div class="article-card">' +
            '<a href="' + articleUrl + '">' +
            (heroSrc ? '<img class="card-thumb" src="' + heroSrc + '" alt="' + article.title + '" loading="lazy">' : '') +
            '<div class="article-tag">' + meta.tag + '</div>' +
            '<h4>' + article.title + '</h4>' +
            '<p>' + article.excerpt + '</p>' +
            '<div class="card-date">' + displayDate + '</div>' +
            '</a>' +
            '</div>';
    }

    // New combined-grid path: single #articlesGrid with chip filters.
    var combinedGrid = document.getElementById('articlesGrid');
    if (combinedGrid) {
        if (!activeCats.length) {
            combinedGrid.innerHTML = NO_CATEGORIES;
            return;
        }

        var matched = publishedArticles.filter(function(a) {
            if (activeCats.indexOf(a.type) === -1) return false;
            if (!terms.length) return true;
            return matchesQuery(articleHaystack(a), terms);
        });

        // Sort newest first
        matched.sort(function(a, b) { return (b.date || '').localeCompare(a.date || ''); });

        if (!matched.length) {
            combinedGrid.innerHTML = query ? NO_RESULTS_SEARCH : EMPTY_MESSAGE;
            return;
        }
        combinedGrid.innerHTML = matched.map(buildCardHtml).join('');
        return;
    }

    // Legacy path: per-category grids (kept so this script stays drop-in safe).
    document.querySelectorAll('.articles-grid[data-category]').forEach(function(grid) {
        var category = grid.dataset.category;
        var catArticles = publishedArticles.filter(function(a) { return a.type === category; });
        if (terms.length) {
            catArticles = catArticles.filter(function(a) {
                return matchesQuery(articleHaystack(a), terms);
            });
        }
        if (!catArticles.length) {
            grid.innerHTML = query ? NO_RESULTS_SEARCH : EMPTY_MESSAGE;
            return;
        }
        catArticles.sort(function(a, b) { return (b.date || '').localeCompare(a.date || ''); });
        grid.innerHTML = catArticles.map(buildCardHtml).join('');
    });
}

document.addEventListener('DOMContentLoaded', function() {
    var searchInput = document.getElementById('articleSearch');
    function currentQuery() { return searchInput ? searchInput.value : ''; }

    // Wire category chips as single-select. Clicking a chip activates only that
    // chip and deactivates the rest. The "all" chip resets to every category.
    var allChips = document.querySelectorAll('.filter-chip[data-category]');
    allChips.forEach(function(chip) {
        chip.addEventListener('click', function() {
            allChips.forEach(function(c) {
                c.classList.remove('active');
                c.setAttribute('aria-pressed', 'false');
            });
            chip.classList.add('active');
            chip.setAttribute('aria-pressed', 'true');
            renderArticles(currentQuery());
        });
    });

    renderArticles();

    if (searchInput) {
        var clearBtn = document.getElementById('articleSearchClear');
        function syncClearBtn() {
            if (clearBtn) clearBtn.hidden = !searchInput.value.length;
        }
        var debounceTimer;
        searchInput.addEventListener('input', function() {
            syncClearBtn();
            clearTimeout(debounceTimer);
            debounceTimer = setTimeout(function() { renderArticles(searchInput.value); }, 200);
        });
        if (clearBtn) {
            clearBtn.addEventListener('click', function() {
                searchInput.value = '';
                syncClearBtn();
                renderArticles('');
                searchInput.focus();
            });
        }
        syncClearBtn();
    }
});
