// ===== Published Articles - single source of truth =====
// Generated by /admin/article-manager.html - Article Manager
// You can also edit this file manually if preferred.

const publishedArticles = [
    {
        "type": "travel",
        "title": "Bahamas Cruising Permit Changes - April 2026",
        "excerpt": "Bahamas cruising permit fees changed again — effective April 1, 2026. If you're yacht shopping with the Bahamas on your radar, these new costs are part of the ownership conversation. Here's what you need to know.",
        "date": "2026-05-05",
        "author": "Clark Haley",
        "slug": "bahamas-cruising-permit-changes-april-2026",
        "fileName": "2026-05-05-bahamas-cruising-permit-changes-april-2026.html",
        "heroImage": "bahamascrusingpermits.jpg",
        "keywords": "Bahamas cruising permit 2026, Bahamas cruising fees updated, how much does it cost to cruise the Bahamas, Bahamas boat permit Florida, yacht cruising Bahamas from Florida, Bahamas FDCC permit, yacht broker Bahamas cruising advice, Palm Beach yacht broker"
    },
    {
        "type": "boat-reviews",
        "title": "World Premiere - Riviera 6200 Sport Yacht",
        "excerpt": "Riviera's new 6200 Sport Yacht delivers big-boat living in 62 feet — full-beam master, alfresco aft deck, gourmet galley, and twin Volvo Penta 900hp IPS drives. This one is built to cruise in serious style.",
        "date": "2026-05-04",
        "author": "Clark Haley",
        "slug": "world-premiere-riviera-6200-sport-yacht",
        "fileName": "2026-05-04-world-premiere-riviera-6200-sport-yacht.html",
        "heroImage": "01-riviera-6200-sport-yacht-platinum-edition-running-02.jpg",
        "keywords": "Riviera, Sport Yacht, Motor Yacht"
    },
    {
        "type": "industry-news",
        "title": "Sunseeker gets a new permanent CEO",
        "excerpt": "Sunseeker completed the sale of the company to investment group. New owners first objective? Hire a new and permanent CEO",
        "date": "2026-04-03",
        "author": "Clark Haley",
        "slug": "sunseeker-gets-a-new-permanent-ceo",
        "fileName": "2026-04-03-sunseeker-gets-a-new-permanent-ceo.html",
        "heroImage": "sunseekerceo.jpg",
        "keywords": "Sunseeker Yachts, Sunseeker CEO, Sunseeker Yachts news, Sunseeker leadership, One Water Yacht Group, OWYG, Sunseeker acquisition, Sunseeker dealer network, Sunseeker yachts for sale, Sunseeker yacht broker Florida, luxury yacht news, Clark Haley, Haley Yachts"
    }
];

function renderArticles(searchTerm) {
    var CATEGORY_META = {
        'boat-reviews':  { tag: 'Boat Review',   label: 'Boat Reviews' },
        'newsletters':   { tag: 'Newsletter',    label: 'Newsletters' },
        'how-to':        { tag: 'How To',        label: 'How To' },
        'travel':        { tag: 'Travel',        label: 'Travel' },
        'industry-news': { tag: 'Industry News', label: 'Industry News' }
    };

    var EMPTY_MESSAGE = '<p style="color:#999;font-style:italic;font-size:0.9rem;">No articles published yet. Check back soon.</p>';
    var NO_RESULTS = '<p style="color:#999;font-style:italic;font-size:0.9rem;">No articles match your search.</p>';
    var query = (searchTerm || '').toLowerCase().trim();

    document.querySelectorAll('.articles-grid[data-category]').forEach(function(grid) {
        var category = grid.dataset.category;
        var catArticles = publishedArticles.filter(function(a) { return a.type === category; });
        var meta = CATEGORY_META[category];

        if (query) {
            catArticles = catArticles.filter(function(a) {
                return (a.title || '').toLowerCase().indexOf(query) !== -1 ||
                       (a.excerpt || '').toLowerCase().indexOf(query) !== -1 ||
                       (a.keywords || '').toLowerCase().indexOf(query) !== -1 ||
                       (a.author || '').toLowerCase().indexOf(query) !== -1;
            });
        }

        if (!catArticles.length) {
            grid.innerHTML = query ? NO_RESULTS : EMPTY_MESSAGE;
            return;
        }

        grid.innerHTML = catArticles.map(function(article) {
            var date = new Date(article.date + 'T12:00:00');
            var displayDate = date.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
            var heroSrc = article.heroImage
                ? 'articles/' + category + '/images/' + article.heroImage
                : '';
            var articleUrl = 'articles/' + category + '/' + article.fileName;

            return '<div class="article-card">' +
                '<a href="' + articleUrl + '">' +
                (heroSrc ? '<img class="card-thumb" src="' + heroSrc + '" alt="' + article.title + '" loading="lazy">' : '') +
                '<div class="article-tag">' + meta.tag + '</div>' +
                '<h4>' + article.title + '</h4>' +
                '<p>' + article.excerpt + '</p>' +
                '<div class="card-date">' + displayDate + '</div>' +
                '</a>' +
                '</div>';
        }).join('');
    });
}

document.addEventListener('DOMContentLoaded', function() {
    renderArticles();
    var searchInput = document.getElementById('articleSearch');
    if (searchInput) {
        var debounceTimer;
        searchInput.addEventListener('input', function() {
            clearTimeout(debounceTimer);
            var val = searchInput.value;
            debounceTimer = setTimeout(function() { renderArticles(val); }, 200);
        });
    }
});
