// ===== Published Articles - single source of truth =====
// Generated by /admin/article-manager.html - Article Manager
// You can also edit this file manually if preferred.

const publishedArticles = [
    {
        "type": "industry-news",
        "title": "Sunseeker gets a new permanent CEO",
        "excerpt": "Sunseeker completed the sale of the company to investment group. New owners first objective? Hire a new and permanent CEO",
        "date": "2026-04-03",
        "author": "Clark Haley",
        "slug": "sunseeker-gets-a-new-permanent-ceo",
        "fileName": "2026-04-03-sunseeker-gets-a-new-permanent-ceo.html",
        "heroImage": "sunseekerceo.jpg",
        "keywords": "Sunseeker Yachts, Denison Yachts, One Water Yacht Group, Clark Haley, Yacht Broker"
    }
];

function renderArticles(searchTerm) {
    var CATEGORY_META = {
        'boat-reviews':  { tag: 'Boat Review',   label: 'Boat Reviews' },
        'newsletters':   { tag: 'Newsletter',    label: 'Newsletters' },
        'how-to':        { tag: 'How To',        label: 'How To' },
        'travel':        { tag: 'Travel',        label: 'Travel' },
        'industry-news': { tag: 'Industry News', label: 'Industry News' }
    };

    var EMPTY_MESSAGE = '<p style="color:#999;font-style:italic;font-size:0.9rem;">No articles published yet. Check back soon.</p>';
    var NO_RESULTS = '<p style="color:#999;font-style:italic;font-size:0.9rem;">No articles match your search.</p>';
    var query = (searchTerm || '').toLowerCase().trim();

    document.querySelectorAll('.articles-grid[data-category]').forEach(function(grid) {
        var category = grid.dataset.category;
        var catArticles = publishedArticles.filter(function(a) { return a.type === category; });
        var meta = CATEGORY_META[category];

        if (query) {
            catArticles = catArticles.filter(function(a) {
                return (a.title || '').toLowerCase().indexOf(query) !== -1 ||
                       (a.excerpt || '').toLowerCase().indexOf(query) !== -1 ||
                       (a.keywords || '').toLowerCase().indexOf(query) !== -1 ||
                       (a.author || '').toLowerCase().indexOf(query) !== -1;
            });
        }

        if (!catArticles.length) {
            grid.innerHTML = query ? NO_RESULTS : EMPTY_MESSAGE;
            return;
        }

        grid.innerHTML = catArticles.map(function(article) {
            var date = new Date(article.date + 'T12:00:00');
            var displayDate = date.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
            var heroSrc = article.heroImage
                ? 'articles/' + category + '/images/' + article.heroImage
                : '';
            var articleUrl = 'articles/' + category + '/' + article.fileName;

            return '<div class="article-card">' +
                '<a href="' + articleUrl + '">' +
                (heroSrc ? '<img class="card-thumb" src="' + heroSrc + '" alt="' + article.title + '" loading="lazy">' : '') +
                '<div class="article-tag">' + meta.tag + '</div>' +
                '<h4>' + article.title + '</h4>' +
                '<p>' + article.excerpt + '</p>' +
                '<div class="card-date">' + displayDate + '</div>' +
                '</a>' +
                '</div>';
        }).join('');
    });
}

document.addEventListener('DOMContentLoaded', function() {
    renderArticles();
    var searchInput = document.getElementById('articleSearch');
    if (searchInput) {
        var debounceTimer;
        searchInput.addEventListener('input', function() {
            clearTimeout(debounceTimer);
            var val = searchInput.value;
            debounceTimer = setTimeout(function() { renderArticles(val); }, 200);
        });
    }
});
